# Generated by Django 5.2 on 2025-06-09 22:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('NEW_ORDER', 'New Order'), ('ORDER_STATUS_UPDATE', 'Order Status Update'), ('PRODUCT_STOCK_ALERT', 'Product Stock Alert'), ('NEW_MESSAGE', 'New Message'), ('SYSTEM_ALERT', 'System Alert'), ('PROMOTION', 'Promotion'), ('OTHER', 'Other')], max_length=50)),
                ('content', models.TextField(blank=True, null=True)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesPersonNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.notification')),
            ],
            bases=('notifications.notification',),
        ),
        migrations.CreateModel(
            name='CustomerNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.notification')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('notifications.notification',),
        ),
    ]
