# Generated by Django 5.2 on 2025-05-26 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_useraccount_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="profile",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profile_accounts",
                to="core.profile",
            ),
        ),
    ]
